### PR TITLE
[Task 4] Integration with db

### PR DESCRIPTION
**Pull request by AlexNo**
- [x]  1 - Task 4.1 is implemented
- [x]  3 - TASK 4.2 is implemented lambda links are provided and returns data
- [x]  4 - TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
- [x]  5 - Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.

Additional (optional) tasks

- [x]  +1 - POST/products lambda functions returns error 400 status code if product data is invalid
- [x]  +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [x]  +1 - All lambdas do console.log for each incoming requests and their arguments
- [x]  +1 - Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa)

All main + additional requirements are met.

Cloudfront URL: [https://de99qfjzvg3qn.cloudfront.net/](https://de99qfjzvg3qn.cloudfront.net/)

API:
GET by ID: [https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/product/{ID}](https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/product/b5dbd52e-d555-4f25-8b5a-9d509c6cc7df) 
GET list: [https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/products](https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/products)
POST create: [https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/product](https://8x993dg02g.execute-api.eu-west-1.amazonaws.com/dev/product)

### CODE REVIEW

**Review by mvedataydin — APPROVED** [review]
Hello @AlexNo, good job on the PR!
This is my cross-check review, please let me know if I am missing anything:
Cross-check score: 9/9
- [x]  Task 4.1 is implemented
- [x]  Task 4.2 is implemented lambda links are provided and returns data
- [x]  Task 4.3 is implemented lambda links are provided and products is stored in DB (call Task 4.2 to see the product)
- [x]  Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. Link to a working Frontend application is provided for cross-check reviewer.
- [x]  POST /products lambda functions returns error 400 status code if product data is invalid
- [x]  All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [x]  All lambdas do console.log for each incoming requests and their arguments
- [x]  Transaction based creation of product (couldn't tested it, reveiving an error  from create product function)
Screen Shot 2022-07-31 at 14 16 03

**Comment by AlexNo** [comment]
Hi, @mvedataydin, thanks for your review!
I believe that POST request didn't work in your test due to incorrect Content-Type header, I see "Text" instead of "application/json" which is expected. Could you check one more time?

Thanks !

**Comment by mvedataydin** [comment]
Hello @AlexNo, yes you are right, It was my bad. The POST request is working as expected. I updated the cross-check review as 9/9. 
Thanks!

**Review by shekharverma17 — COMMENTED** [review]
Hey @AlexNo, I reviewed and updated my cross check review score here as 9/9.
RS app option to submit review score is disabled now for me so updating here.

**Pull request merged**
